### ISSUE TITLE
data need

### ISSUE THREAD

**Issue by huanhexiao** [wystephen/ComplexityPositioning#1]
hi, 
you've reminded  in gtsam_GPS_INS_test.cpp,that there is a file called imuAndGPSdata.csv,but i could not find it ,could u please share it for me?
 
Thank u.
best wishes

**Comment by wystephen** [comment]
Such file could be found at gtsam library. (gtsam/examples/Data/)

**Comment by huanhexiao** [comment]
Copy that，thank u
